apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: andrsmlz/mlflow:latest
          ports:
            - containerPort: 5001
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: global-env
                  key: MINIO_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: global-env
                  key: MINIO_SECRET_KEY
          command: ["mlflow"]
          args:
            - server
            - "--host=0.0.0.0"
            - "--port=5001"
            - "--backend-store-uri=postgresql://mlflow:mlflow123@postgres:5432/mlflow"
            - "--default-artifact-root=s3://mlflow/"
          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc
