FROM python:3.9-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN pip install --no-cache-dir streamlit requests

WORKDIR /app
COPY streamlit/ /app

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
