FROM python:3.9-slim

# Evitar interacción en instalaciones
ENV DEBIAN_FRONTEND=noninteractive

# Instalar FastAPI, Uvicorn y MLflow
RUN pip install --no-cache-dir fastapi uvicorn[standard] mlflow pandas

# Crear carpeta de trabajo
WORKDIR /app

# Copiar el código de la API
COPY fastapi/ /app

# Puerto que usará Uvicorn
EXPOSE 5000

# Comando para ejecutar la API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
